/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plan_rutas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AndresD
 */
public class rutas extends javax.swing.JFrame {

    /**
     * Creates new form rutas
     */
    public rutas() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtOrigen = new javax.swing.JTextField();
        TxtDestino = new javax.swing.JTextField();
        TxtFecha = new javax.swing.JTextField();
        TxtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 260, 30));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No.bus");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No.Conductor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destino");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Origen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva ruta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jPanel1.add(TxtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));
        jPanel1.add(TxtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, -1));
        jPanel1.add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, -1));
        jPanel1.add(TxtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Rutas", "Origen", "Destino", "No.Bus", "Fecha", "Hora", "No.Conductor"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 600, 260));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel10.setText("Historial de rutas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 150, 30));
        jPanel1.add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 190, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No-bus", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tricar/ICONOS/Recurso 4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 170, -1));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Variables
    ArrayList<ruta> rtList = new ArrayList();
    DefaultTableModel model;
    String url="jdbc:sqlite:C:/Users/Rachel/Documents/TriCARdb.db"; 
    Connection conectar; 
    int posi=0;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
       conectar =DriverManager.getConnection(url); 
       if(conectar!=null){
       String agg="insert into Rutas (Origen, Destino, No_Bus, Fecha, Hora,No_Conducor)" + "values "
+ "('"+this.TxtOrigen.getText()+"','"+this.TxtDestino.getText()+"',"+this.jComboBox2.getSelectedItem()+",'"+this.TxtFecha.getText()+"',"
               + ""+this.TxtHora.getText()+","+this.txtEmpleado.getText()+")";
       
       PreparedStatement bd= conectar.prepareStatement(agg);
       bd.execute();
       JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
       
      ResultSet result=null; 
       bd=conectar.prepareStatement("select No_Rutas, Origen, Destino, No_Bus, Fecha, Hora, No_Conducor from Rutas");
                
       result=bd.executeQuery();
       
       while(result.next()){
       model.addRow(new Object[]{result.getInt("No_Rutas"),result.getString("Origen"),result.getString("Destino"),result.getInt("No_Bus"), 
                   result.getString("Fecha"), result.getInt("Hora"), result.getInt("No_Conducor")});
       
       } 
       conectar.close();
       }
       }catch(Exception x){
        JOptionPane.showMessageDialog(null, x.getMessage().toString());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel model=(DefaultTableModel)this .jTable1.getModel();
int i=jTable1.getSelectedRow();

if(i>7000){
    
}else{
   TxtOrigen.setText(String.valueOf(jTable1.getValueAt(i, 2)));
   TxtDestino.setText(String.valueOf(jTable1.getValueAt(i, 1)));
   jComboBox2.setSelectedItem(String.valueOf(jTable1.getValueAt(i, 3)));
   TxtFecha.setText(String.valueOf(jTable1.getValueAt(i, 4)));
   TxtHora.setText(String.valueOf(jTable1.getValueAt(i, 5)));
   txtEmpleado.setText(String.valueOf(jTable1.getValueAt(i, 6)));
   
}
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
       conectar =DriverManager.getConnection(url); 
       if(conectar!=null){
       
       model.setRowCount(0); 
       
       ResultSet result=null; 
       PreparedStatement bd=conectar.prepareStatement("select No_Rutas, Origen, Destino, No_Bus, Fecha, Hora, No_Conducor from Rutas");
                
       result=bd.executeQuery();
       
       while(result.next()){
       model.addRow(new Object[]{result.getInt("No_Rutas"),result.getString("Origen"),result.getString("Destino"),result.getInt("No_Bus"), 
                   result.getString("Fecha"), result.getInt("Hora"), result.getInt("No_Conducor")});
       } 
       conectar.close();
       }
       }catch(Exception x){
       JOptionPane.showMessageDialog(null, x.getMessage().toString());
       }
    }//GEN-LAST:event_jButton2ActionPerformed
   void presentar(int i){
    if(i>=0 && i<rtList.size()){
        
        this.TxtOrigen.setText(rtList.get(i).getOrigen());
        this.TxtDestino.setText(rtList.get(i).getDestino());
       
        this.txtEmpleado.setText(String.valueOf(rtList.get(i).getNoEmpleado()));
        this.TxtFecha.setText(rtList.get(i).getFecha());
        this.TxtHora.setText(String.valueOf(rtList.get(i).getHora())); 
        
    }
    }
    private void PresentarTabla(){
       model.setRowCount(0); 
       for(int i=0; i<rtList.size(); i++){
       model.addRow(new Object[]{rtList.get(i).getNoRuta(), rtList.get(i).getOrigen(), rtList.get(i).getDestino(),
                                 rtList.get(i).getNoConductor(),rtList.get(i).getNoEmpleado() ,rtList.get(i).getNoBus(), 
                                 rtList.get(i).getFecha(), rtList.get(i).getHora()});
   
        }

    }
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDestino;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtHora;
    private javax.swing.JTextField TxtOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmpleado;
    // End of variables declaration//GEN-END:variables
}
