/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidad_buses;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rachel
 */
public class registro_buses extends javax.swing.JFrame {

    /**
     * Creates new form registro_buses
     */
    public registro_buses() {
        initComponents();
        setLocationRelativeTo(null);
        buses=(DefaultTableModel) jTable1.getModel(); 
    }
    ArrayList<buses> arr= new ArrayList(); 
    DefaultTableModel buses; 
    String url="jdbc:sqlite:C:/Users/Rachel/Documents/TriCARdb.db"; 
    Connection conectar; 
    int posi=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_año = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_numasien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_pasajeros = new javax.swing.JTextField();
        btn_agreg = new javax.swing.JButton();
        btn_cer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_mode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_carga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de Placa");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel2.add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel2.add(txt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Número de Asientos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel2.add(txt_numasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 160, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacidad de Pasajeros");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel2.add(txt_pasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, -1));

        btn_agreg.setText("Agregar");
        btn_agreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 240, 30));

        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 240, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modelo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel2.add(txt_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Bus", "Num Placa", "Modelo", "Año", "Color", "Num Asientos", "Capacidad Pas", "Carga"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 600, 380));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Capacidad de Carga");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel2.add(txt_carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUSES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 200, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tricar/ICONOS/Recurso 4.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 610));

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model=(DefaultTableModel)this .jTable1.getModel();
int i=jTable1.getSelectedRow();

if(i>7000){
    
}else{
   txt_mode.setText(String.valueOf(jTable1.getValueAt(i, 2)));
   txtPlaca.setText(String.valueOf(jTable1.getValueAt(i, 1)));
   txt_año.setText(String.valueOf(jTable1.getValueAt(i, 3)));
   txt_color.setText(String.valueOf(jTable1.getValueAt(i, 4)));
   txt_numasien.setText(String.valueOf(jTable1.getValueAt(i, 5)));
   txt_pasajeros.setText(String.valueOf(jTable1.getValueAt(i, 6)));
   txt_carga.setText(String.valueOf(jTable1.getValueAt(i, 7)));
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerActionPerformed

    private void btn_agregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregActionPerformed
       try{
       conectar =DriverManager.getConnection(url); 
       if(conectar!=null){
       String agg="insert into buses (Num_placa, Modelo, Año, Color, num_asien,Capa_Pasajeros,carga)" + "values "
+ "('"+this.txtPlaca.getText()+"','"+this.txt_mode.getText()+"',"+this.txt_año.getText()+",'"+this.txt_color.getText()+"',"
               + ""+this.txt_numasien.getText()+","+this.txt_pasajeros.getText()+","+this.txt_carga.getText()+")";
       
       PreparedStatement bd= conectar.prepareStatement(agg);
       bd.execute();
       JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
       
       ResultSet result=null; 
       bd= conectar.prepareStatement("select  Num_bus,Num_placa ,Modelo, Año, "
                                                       + "Color, num_asien,Capa_Pasajeros,carga from buses");
       result=bd.executeQuery();
       
       while(result.next()){
       buses.addRow(new Object []{result.getInt("Num_bus"),result.getString("Num_placa"),result.getString("Modelo"),
                                 result.getInt("Año"),result.getString("Color"),result.getInt("num_asien"),result.getInt("Capa_Pasajeros")
                                 ,result.getInt("carga")});
       } 
       conectar.close();
       }
       }catch(Exception x){
        JOptionPane.showMessageDialog(null, x.getMessage().toString());
       }

    }//GEN-LAST:event_btn_agregActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
       conectar =DriverManager.getConnection(url); 
       if(conectar!=null){
       
       buses.setRowCount(0); 
       
       ResultSet result=null; 
       PreparedStatement bd=conectar.prepareStatement("select Num_bus, Num_placa, Modelo, Año, Color, Num_asien, Capa_Pasajeros, carga from buses");
                
       result=bd.executeQuery();
       
       while(result.next()){
       buses.addRow(new Object[]{result.getInt("Num_bus"),result.getString("Num_placa"),result.getString("Modelo"),result.getInt("Año"), 
                   result.getString("Color"), result.getInt("Num_asien"), result.getInt("Capa_Pasajeros"), result.getInt("carga")});
       } 
       conectar.close();
       }
       }catch(Exception x){
       JOptionPane.showMessageDialog(null, x.getMessage().toString());
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    void limpiar(){
    this.txtPlaca.setText("");
    this.txt_año.setText("");
    this.txt_color.setText(""); 
    this.txt_numasien.setText("");
    this.txt_pasajeros.setText(""); 
    this.txt_mode.setText(""); 
    this.txt_carga.setText("");
    }
    
    void pres_datos(int i){
    if(i>=0 && i<arr.size()){
    this.txt_mode.setText(arr.get(i).getModelo()); 
    this.txtPlaca.setText(arr.get(i).getPlaca()); 
    this.txt_año.setText(String.valueOf(arr.get(i).getAño()));
    this.txt_color.setText(arr.get(i).getColor());
    this.txt_numasien.setText(String.valueOf(arr.get(i).getNum_asientos()));
    this.txt_pasajeros.setText(String.valueOf(arr.get(i).getCantidad_pasajeros()));
    this.txt_carga.setText(String.valueOf(arr.get(i).getCarga()));
    }
    }
    
    void pres_table(){
   buses.setRowCount(0); 
   for(int i=0; i<arr.size(); i++){
   buses.addRow(new Object[]{arr.get(i).getNum_bus(),arr.get(i).getModelo(),arr.get(i).getPlaca(),arr.get(i).getAño(), arr.get(i).getColor(),
                             arr.get(i).getNum_asientos(), arr.get(i).getCantidad_pasajeros(), arr.get(i).getCarga()});
   
   }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_buses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agreg;
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_carga;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_mode;
    private javax.swing.JTextField txt_numasien;
    private javax.swing.JTextField txt_pasajeros;
    // End of variables declaration//GEN-END:variables
}
